name: Valida Fluxo Git

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main
      - develop

jobs:
  valida-origem-main:
    runs-on: ubuntu-latest
    steps:
      - name: Bloquear PR para a main que não venha da develop
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "::error::Regra violada! A branch 'main' só aceita PRs vindos da 'develop'."
          echo "Destino: ${{ github.base_ref }}"
          echo "Origem: ${{ github.head_ref }}"
          exit 1

      - name: Sucesso
        if: github.base_ref != 'main' || github.head_ref == 'develop'
        run: |
          echo "Validação aprovada para o destino ${{ github.base_ref }} a partir de ${{ github.head_ref }}."
